---
- name: Change User Password
  hosts: databases
  become: yes

  tasks:
    - name: Change user password
      user:
        name: isofh
        update_password: always
        password: "{{ new_password }}"
      vars:
        new_password: 'Huynn@9890'