---
- name: Copy SSH key to servers
  hosts: servers
  gather_facts: true
  become: yes

  vars_files:
      - vars.yml
      
  tasks:
    - name: Copy SSH key to authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', "{{ path_sshkey_rsa_pub }}") }}"
        state: present