#[servers]
#prometheus ansible_host=10.0.0.235 ansible_connection=ssh ansible_ssh_pass=Huynn@9890#!
#jira ansible_host=10.0.0.176 ansible_connection=ssh ansible_ssh_pass=Huynn@9890#!
#prometheus_production ansible_host=10.0.0.13 ansible_connection=ssh ansible_ssh_pass=HuyNgNg@9890#!
#
#[databases]
#db_jira_master ansible_host=10.0.0.132 ansible_connection=ssh ansible_ssh_pass=Huynn@9890#!

all:
    children:
        servers:
            hosts:
                prometheus:
                    ansible_host: 10.0.0.235
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"

                prometheus_production:
                    ansible_host: 10.0.0.13
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "HuyNgNg@9890#!"

                jira:
                    ansible_host: 10.0.0.176
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"
            vars:

        databases:
            hosts:
                db_mysql_master:
                    ansible_host: 10.0.0.187
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"

        database_slave:
            hosts:
                db_jira_slave:
                    ansible_host: 10.0.0.133
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"
                    ansible_become_pass: "Huynn@9890#!"

        database_postgresql:
            hosts:
                postgresql:
                    ansible_host: 10.0.0.135
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"
                    ansible_become_pass: "Huynn@9890#!"

        web_server:
            hosts:
                jira_worker:
                    ansible_host: 10.0.0.172
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"
        
        server_test:
             hosts:
                test:
                    ansible_host: 10.0.0.108
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "123123"
