#[servers]
#prometheus ansible_host=10.0.0.235 ansible_connection=ssh ansible_ssh_pass=Huynn@9890#!
#jira ansible_host=10.0.0.176 ansible_connection=ssh ansible_ssh_pass=Huynn@9890#!
#prometheus_production ansible_host=10.0.0.13 ansible_connection=ssh ansible_ssh_pass=HuyNgNg@9890#!
#
#[databases]
#db_jira_master ansible_host=10.0.0.132 ansible_connection=ssh ansible_ssh_pass=Huynn@9890#!

all:
    children:
        servers:
            hosts:
                prometheus:
                    ansible_host: 10.0.0.235
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"

                prometheus_production:
                    ansible_host: 10.0.0.13
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "HuyNgNg@9890#!"

                jira:
                    ansible_host: 10.0.0.176
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "Huynn@9890#!"
            vars:

        databases:
            hosts:
                db_jira_master:
                    ansible_host: 10.0.0.132
                    ansible_connection: ssh
                    ansible_user: isofh
                    ansible_password: "HuyNgNg@9890#!"
