---
- name: Install Mysql
  hosts: database_slave
  become: yes
#  module_defaults:
#      mysql:
#        login_unix_socket: /var/run/mysqld/mysqld.sock
  vars_files:
      - vars.yml

  tasks:
    - name: install new MYSQL database
      apt:
          service: "{{ item }}"
          state: installed
      loop:
          - pip
          - python3-dev
          - mysql-server
          - mysql-client

    - name: pip install mysqlclient
      shell: pip install mysqlclient

    - name: start MYSQL service
      service:
          name: mysql
          state: started
          enable: yes
#      action: service name=mysql state=started

    - name: Remove the test database
      mysql_db: name=test state=absent

    - name: create database
      mysql_db:
          name: "{{ mysql_db_name }}"
          state: present

    - name: create DB user
      mysql_user:
          name: "{{ mysql_user }}"
          password: "{{ mysql_password }}"
          priv: '*.*:ALL,GRANT'
          state: present

    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host=$item state=absent
      loop:
          - 127.0.0.1
          - ::1
          - localhost

    - name: Copy .my.cnf file with root password credentials
      template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password={{mysql_root_password}}
      loop:
          - 127.0.0.1
          - ::1
          - localhost