---
- name: Install Mysql
  hosts: database_slave

  vars_files:
      - vars.yml

  tasks:
    - name: install new MYSQL database
      apt:
          service: "{{ item }}"
          state: installed
      loop:
          - mysql-server
          - mysql-client

    - name: start MYSQL service
      service:
          name: mysql
          state: started
          enable: yes

    - name: create database
      mysql_db:
          name: "{{ mysql_db_name }}"
          state: present

    - name: create DB user
      mysql_user:
          name: "{{ mysql_user }}"
          password: "{{ mysql_password }}"
          priv: '*.*:ALL'
          state: present
